"""
Step 2: Export trained XGBoost model to C code for nRF52840 deployment.

Generates:
  sleep_model/sleep_model.h    - XGBoost inference function (pure C)
  sleep_model/scaler_params.h  - Scaler means and stds as C arrays
  sleep_model/features.h       - Feature index constants

Usage in Arduino:
  #include "sleep_model/sleep_model.h"
  #include "sleep_model/scaler_params.h"

  double input[NUM_FEATURES];   // fill with scaled feature values
  double output[3];              // Wake, NREM, REM probabilities
  score(input, output);          // call generated function
  int stage = argmax(output, 3); // 0=Wake, 1=NREM, 2=REM

Requirements:
  pip install m2cgen
"""

import pickle
import numpy as np
import os
import xgboost as xgb
import m2cgen as m2c

# ============================================================================
# LOAD ARTIFACTS
# ============================================================================

print("Loading chip model artifacts...")

with open('scaler_chip.pkl', 'rb') as f:
    scaler = pickle.load(f)

with open('feature_names_chip.pkl', 'rb') as f:
    feature_names = pickle.load(f)

# Load booster directly - m2cgen can handle this
model = xgb.Booster()
model.load_model('xgboost_chip_model.json')

n_features = len(feature_names)
n_trees = len(model.get_dump())
print(f"  {n_features} features, {n_trees} trees loaded")

# ============================================================================
# CREATE OUTPUT DIRECTORY
# ============================================================================

os.makedirs('sleep_model', exist_ok=True)

# ============================================================================
# EXPORT MODEL TO C (m2cgen)
# ============================================================================

print("\nConverting XGBoost to C code via m2cgen...")

c_code = m2c.export_to_c(model, function_name='score')

# m2cgen generates: void score(double* input, double* output)
# output[0] = P(Wake), output[1] = P(NREM), output[2] = P(REM)

header = f"""/*
 * Auto-generated by export_to_c.py — DO NOT EDIT MANUALLY
 *
 * XGBoost sleep stage classifier ({n_features} features, {n_trees} trees)
 * Classes: 0=Wake, 1=NREM, 2=REM
 *
 * Usage:
 *   double input[{n_features}];   // scaled features (apply scaler_params.h first)
 *   double output[3];             // receives class probabilities
 *   score(input, output);
 *   int stage = 0;
 *   for (int i = 1; i < 3; i++) if (output[i] > output[stage]) stage = i;
 */

#ifndef SLEEP_MODEL_H
#define SLEEP_MODEL_H

#define NUM_FEATURES {n_features}

"""

footer = "\n#endif // SLEEP_MODEL_H\n"

with open('sleep_model/sleep_model.h', 'w') as f:
    f.write(header)
    f.write(c_code)
    f.write(footer)

model_size = os.path.getsize('sleep_model/sleep_model.h')
print(f"  sleep_model/sleep_model.h  ({model_size/1024:.1f} KB)")

# ============================================================================
# EXPORT SCALER PARAMETERS AS C ARRAYS
# ============================================================================

print("Exporting scaler parameters...")

means  = scaler.mean_
scales = scaler.scale_

scaler_h = f"""/*
 * Auto-generated StandardScaler parameters — DO NOT EDIT MANUALLY
 * Apply BEFORE calling score():
 *
 *   for (int i = 0; i < NUM_FEATURES; i++) {{
 *       input[i] = (raw[i] - SCALER_MEAN[i]) / SCALER_SCALE[i];
 *   }}
 */

#ifndef SCALER_PARAMS_H
#define SCALER_PARAMS_H

#include <stdint.h>

#define NUM_FEATURES {n_features}

static const double SCALER_MEAN[{n_features}] = {{
"""

# Write means
for i, (name, mean) in enumerate(zip(feature_names, means)):
    comma = ',' if i < n_features - 1 else ''
    scaler_h += f"    {mean:.8f}{comma}  // {i}: {name}\n"

scaler_h += f"""
}};

static const double SCALER_SCALE[{n_features}] = {{
"""

# Write scales
for i, (name, scale) in enumerate(zip(feature_names, scales)):
    comma = ',' if i < n_features - 1 else ''
    scaler_h += f"    {scale:.8f}{comma}  // {i}: {name}\n"

scaler_h += "\n};\n\n#endif // SCALER_PARAMS_H\n"

with open('sleep_model/scaler_params.h', 'w') as f:
    f.write(scaler_h)

scaler_size = os.path.getsize('sleep_model/scaler_params.h')
print(f"  sleep_model/scaler_params.h ({scaler_size/1024:.1f} KB)")

# ============================================================================
# EXPORT FEATURE INDEX CONSTANTS
# ============================================================================

print("Exporting feature index constants...")

features_h = f"""/*
 * Auto-generated feature indices — DO NOT EDIT MANUALLY
 * Use these to fill the input[] array in the correct order.
 */

#ifndef FEATURES_H
#define FEATURES_H

// Raw features (fill from sensors)
"""

for i, name in enumerate(feature_names):
    const_name = name.upper().replace('-', '_').replace('.', '_')
    features_h += f"#define FEAT_{const_name:50s} {i}\n"

features_h += f"""
// Total features
#define NUM_FEATURES {n_features}

#endif // FEATURES_H
"""

with open('sleep_model/features.h', 'w') as f:
    f.write(features_h)

print(f"  sleep_model/features.h")

# ============================================================================
# FLASH SIZE ESTIMATE
# ============================================================================

print()
print("=" * 60)
print("FLASH SIZE ESTIMATE (nRF52840 has 1 MB)")
print("=" * 60)

# The .h file is not exactly flash usage (compiler compresses/optimizes)
# but it's a rough upper bound
model_kb   = model_size / 1024
scaler_kb  = scaler_size / 1024
arduino_kb = 100  # rough Arduino BLE + core estimate
total_kb   = model_kb + scaler_kb + arduino_kb

print(f"  sleep_model.h (model code):  ~{model_kb:.0f} KB")
print(f"  scaler_params.h (arrays):    ~{scaler_kb:.0f} KB")
print(f"  Arduino core + drivers:      ~{arduino_kb:.0f} KB (estimate)")
print(f"  Total estimate:              ~{total_kb:.0f} KB / 1024 KB")
print()

if total_kb < 800:
    print("  OK — fits with headroom for your application code.")
else:
    print("  WARNING — getting tight. Consider reducing n_estimators.")

print()
print("Next: use sleep_model/ in your Arduino sketch.")
print("See the restructured firmware in: firmware_inference.ino")
