"""
Export audio-enhanced XGBoost model to C headers for nRF52840.

Reads (from src/modeling/ — produced by train_audio_model.py):
  xgboost_audio_model.json
  scaler_audio.pkl
  feature_names_audio.pkl

Writes (to hardware/firmware/SleepClassifier_Audio_XGBoost/sleep_model_audio/):
  xgboost_audio.h   — full XGBoost decision trees as C (via m2cgen)
  scaler_audio.h    — SCALER_MEAN / SCALER_SCALE arrays + apply_scaling()
  features_audio.h  — FEAT_* index #defines  (replaces placeholder)

Requirements:
  pip install m2cgen xgboost

Usage:
  python hardware/model_export/export_audio_to_c.py
  (run from any directory — paths are computed relative to this file)
"""

import pickle
import os
import xgboost as xgb
from micromlgen import port
from pathlib import Path

# ── Paths ─────────────────────────────────────────────────────────────────────

ROOT      = Path(__file__).resolve().parent.parent.parent
MODEL_DIR = ROOT / 'src' / 'modeling'
OUT_DIR   = (ROOT / 'hardware' / 'firmware'
             / 'SleepClassifier_Audio_XGBoost' / 'sleep_model_audio')
OUT_DIR.mkdir(parents=True, exist_ok=True)

# ── Load artifacts ────────────────────────────────────────────────────────────

print("Loading model artifacts from src/modeling/ ...")

with open(MODEL_DIR / 'scaler_audio.pkl', 'rb') as f:
    scaler = pickle.load(f)

with open(MODEL_DIR / 'feature_names_audio.pkl', 'rb') as f:
    feature_names = pickle.load(f)

# Load full sklearn XGBClassifier (needed for m2cgen — JSON booster alone is not supported)
with open(MODEL_DIR / 'xgboost_audio_model.pkl', 'rb') as f:
    model = pickle.load(f)

n_features = len(feature_names)
n_trees    = model.n_estimators
print(f"  {n_features} features  |  {n_trees} trees")

# ── 1. Export model → xgboost_audio.h (m2cgen) ───────────────────────────────

print("\nConverting XGBoost → C via micromlgen (Eloquent format) ...")
eloquent_code = port(model)

# micromlgen generates:
#   Eloquent::ML::Port::XGBClassifier with predict(float* x) → int class

model_h = f"""\
/*
 * Auto-generated by export_audio_to_c.py — DO NOT EDIT MANUALLY
 *
 * Audio-enhanced XGBoost sleep stage classifier
 *   Features : {n_features}  (97 IMU + 20 audio)
 *   Trees    : {n_trees}
 *   Classes  : 0 = Wake  |  1 = NREM  |  2 = REM
 *
 * Usage:
 *   #include "sleep_model_audio/xgboost_audio.h"
 *   #include "sleep_model_audio/scaler_audio.h"
 *
 *   double raw[NUM_FEATURES];     // fill from sensors
 *   double scaled[NUM_FEATURES];
 *   apply_scaling(raw, scaled);
 *
 *   float sf[NUM_FEATURES];
 *   for (int i = 0; i < NUM_FEATURES; i++) sf[i] = (float)scaled[i];
 *
 *   Eloquent::ML::Port::XGBClassifier clf;
 *   int pred = clf.predict(sf);   // 0=Wake 1=NREM 2=REM
 */

#ifndef XGBOOST_AUDIO_H
#define XGBOOST_AUDIO_H

#define NUM_FEATURES {n_features}
#define NUM_CLASSES  3

{eloquent_code}

#endif // XGBOOST_AUDIO_H
"""

out_model = OUT_DIR / 'xgboost_audio.h'
out_model.write_text(model_h)
model_kb = out_model.stat().st_size / 1024
print(f"  xgboost_audio.h   ({model_kb:.1f} KB)")

# ── 2. Export scaler → scaler_audio.h ────────────────────────────────────────

print("Exporting scaler parameters ...")

means  = scaler.mean_
scales = scaler.scale_

lines_mean  = '\n'.join(
    f"    {m:.10f}{',' if i < n_features-1 else ''}  // {i}: {name}"
    for i, (name, m) in enumerate(zip(feature_names, means))
)
lines_scale = '\n'.join(
    f"    {s:.10f}{',' if i < n_features-1 else ''}  // {i}: {name}"
    for i, (name, s) in enumerate(zip(feature_names, scales))
)

scaler_h = f"""\
/*
 * Auto-generated by export_audio_to_c.py — DO NOT EDIT MANUALLY
 * StandardScaler parameters for the 117-feature audio-enhanced model.
 *
 * Call apply_scaling(raw, scaled) before score().
 */

#ifndef SCALER_AUDIO_H
#define SCALER_AUDIO_H

#define NUM_FEATURES {n_features}

static const double SCALER_MEAN[{n_features}] = {{
{lines_mean}
}};

static const double SCALER_SCALE[{n_features}] = {{
{lines_scale}
}};

/* Scale raw feature vector in-place equivalent. */
static inline void apply_scaling(const double raw[{n_features}],
                                  double       out[{n_features}]) {{
    for (int i = 0; i < {n_features}; i++)
        out[i] = (raw[i] - SCALER_MEAN[i]) / SCALER_SCALE[i];
}}

#endif // SCALER_AUDIO_H
"""

out_scaler = OUT_DIR / 'scaler_audio.h'
out_scaler.write_text(scaler_h)
scaler_kb = out_scaler.stat().st_size / 1024
print(f"  scaler_audio.h    ({scaler_kb:.1f} KB)")

# ── 3. Export feature indices → features_audio.h ─────────────────────────────

print("Exporting feature index constants ...")

defines = '\n'.join(
    f"#define FEAT_{name.upper().replace('-','_').replace('.','_'):<50s} {i}"
    for i, name in enumerate(feature_names)
)

features_h = f"""\
/*
 * Auto-generated by export_audio_to_c.py — DO NOT EDIT MANUALLY
 *
 * Feature indices for the 117-feature audio-enhanced model.
 * Generated from feature_names_audio.pkl (training dataset order).
 *
 * IMU features  : indices  0 – {n_features - 21}
 * Audio features: indices {n_features - 20} – {n_features - 1}
 */

#ifndef FEATURES_AUDIO_H
#define FEATURES_AUDIO_H

{defines}

#define NUM_FEATURES {n_features}

#endif // FEATURES_AUDIO_H
"""

out_features = OUT_DIR / 'features_audio.h'
out_features.write_text(features_h)
print(f"  features_audio.h  ({out_features.stat().st_size} bytes)")

# ── Flash size estimate ───────────────────────────────────────────────────────

total_kb = model_kb + scaler_kb + 100   # +100 KB Arduino core estimate

print()
print("=" * 55)
print("Flash size estimate  (nRF52840 = 1024 KB)")
print("=" * 55)
print(f"  xgboost_audio.h   (model trees)  : {model_kb:6.1f} KB")
print(f"  scaler_audio.h    (arrays)        : {scaler_kb:6.1f} KB")
print(f"  Arduino core + drivers            : ~100 KB")
print(f"  Total estimate                    : ~{total_kb:.0f} KB / 1024 KB")
print()

if total_kb < 800:
    print("  OK — fits with headroom.")
elif total_kb < 950:
    print("  CAUTION — tight. Monitor actual flash usage after compile.")
else:
    print("  WARNING — likely exceeds flash.")
    print("  Reduce n_estimators in train_audio_model.py and retrain.")

print()
print("Headers written to:")
print(f"  {OUT_DIR}/")
print()
print("Next step: open Arduino IDE and flash")
print("  hardware/firmware/SleepClassifier_Audio_XGBoost/")
print("  SleepClassifier_Audio_XGBoost.ino")
