/*
 * Auto-generated by export_audio_to_c.py — DO NOT EDIT MANUALLY
 *
 * Feature indices for the 117-feature audio-enhanced model.
 * Generated from feature_names_audio.pkl (training dataset order).
 *
 * IMU features  : indices  0 – 96
 * Audio features: indices 97 – 116
 */

#ifndef FEATURES_AUDIO_H
#define FEATURES_AUDIO_H

#define FEAT_AX_MEAN                                            0
#define FEAT_AX_STD                                             1
#define FEAT_AX_MIN                                             2
#define FEAT_AX_MAX                                             3
#define FEAT_AY_MEAN                                            4
#define FEAT_AY_STD                                             5
#define FEAT_AY_MIN                                             6
#define FEAT_AY_MAX                                             7
#define FEAT_AZ_MEAN                                            8
#define FEAT_AZ_STD                                             9
#define FEAT_AZ_MIN                                             10
#define FEAT_AZ_MAX                                             11
#define FEAT_GX_MEAN                                            12
#define FEAT_GX_STD                                             13
#define FEAT_GX_MIN                                             14
#define FEAT_GX_MAX                                             15
#define FEAT_GY_MEAN                                            16
#define FEAT_GY_STD                                             17
#define FEAT_GY_MIN                                             18
#define FEAT_GY_MAX                                             19
#define FEAT_GZ_MEAN                                            20
#define FEAT_GZ_STD                                             21
#define FEAT_GZ_MIN                                             22
#define FEAT_GZ_MAX                                             23
#define FEAT_TEMPC_MEAN                                         24
#define FEAT_TEMPC_STD                                          25
#define FEAT_TEMPC_MIN                                          26
#define FEAT_TEMPC_MAX                                          27
#define FEAT_ZCR_MEAN                                           28
#define FEAT_ENERGY_STD                                         29
#define FEAT_ENERGY_MAX                                         30
#define FEAT_VERY_LOW_POWER                                     31
#define FEAT_VERY_LOW_RATIO                                     32
#define FEAT_LOW_POWER                                          33
#define FEAT_LOW_RATIO                                          34
#define FEAT_SNORING_POWER                                      35
#define FEAT_MID_POWER                                          36
#define FEAT_MID_RATIO                                          37
#define FEAT_HIGH_POWER                                         38
#define FEAT_HIGH_RATIO                                         39
#define FEAT_SILENCE_RATIO                                      40
#define FEAT_CREST_FACTOR                                       41
#define FEAT_ACC_MAG                                            42
#define FEAT_ACC_MAG_STD                                        43
#define FEAT_ACC_MAG_MAX                                        44
#define FEAT_ACC_MAG_MIN                                        45
#define FEAT_GYRO_MAG                                           46
#define FEAT_GYRO_MAG_STD                                       47
#define FEAT_GYRO_MAG_MAX                                       48
#define FEAT_GYRO_MAG_MIN                                       49
#define FEAT_TOTAL_MOVEMENT                                     50
#define FEAT_TOTAL_MOVEMENT_STD                                 51
#define FEAT_MOVEMENT_RATIO                                     52
#define FEAT_MOVEMENT_BALANCE                                   53
#define FEAT_PATIENT_ACC_MEAN                                   54
#define FEAT_PATIENT_ACC_STD                                    55
#define FEAT_PATIENT_ACC_MEDIAN                                 56
#define FEAT_PATIENT_GYRO_MEAN                                  57
#define FEAT_PATIENT_GYRO_STD                                   58
#define FEAT_PATIENT_WAKE_RATIO                                 59
#define FEAT_ACC_MAG_NORMALIZED                                 60
#define FEAT_GYRO_MAG_NORMALIZED                                61
#define FEAT_ACC_VS_PATIENT_MEDIAN                              62
#define FEAT_ACC_PERCENTILE                                     63
#define FEAT_GYRO_PERCENTILE                                    64
#define FEAT_RELATIVE_ACTIVITY                                  65
#define FEAT_ACC_MAG_PREV                                       66
#define FEAT_GYRO_MAG_PREV                                      67
#define FEAT_TOTAL_MOVEMENT_PREV                                68
#define FEAT_ACC_MAG_DIFF                                       69
#define FEAT_GYRO_MAG_DIFF                                      70
#define FEAT_ACC_MAG_DIFF_ABS                                   71
#define FEAT_GYRO_MAG_DIFF_ABS                                  72
#define FEAT_ACC_MAG_ROLLING_MEAN_3                             73
#define FEAT_ACC_MAG_ROLLING_MEAN_5                             74
#define FEAT_ACC_MAG_ROLLING_STD_3                              75
#define FEAT_ACC_MAG_ROLLING_STD_5                              76
#define FEAT_IS_MOVEMENT_BOUT                                   77
#define FEAT_MOVEMENT_BOUT_COUNT                                78
#define FEAT_IS_STILLNESS                                       79
#define FEAT_STILLNESS_DURATION                                 80
#define FEAT_AX_DOMINANCE                                       81
#define FEAT_AY_DOMINANCE                                       82
#define FEAT_AZ_DOMINANCE                                       83
#define FEAT_TILT_ESTIMATE                                      84
#define FEAT_AX_AY_RATIO                                        85
#define FEAT_POSITION_CHANGE_INDICATOR                          86
#define FEAT_NUM_POSITION_CHANGES                               87
#define FEAT_TIME_SINCE_START_MIN                               88
#define FEAT_SLEEP_CYCLE_PHASE                                  89
#define FEAT_SLEEP_CYCLE_SIN                                    90
#define FEAT_SLEEP_CYCLE_COS                                    91
#define FEAT_ACC_COEFFICIENT_OF_VARIATION                       92
#define FEAT_GYRO_COEFFICIENT_OF_VARIATION                      93
#define FEAT_ACC_RANGE                                          94
#define FEAT_GYRO_RANGE                                         95
#define FEAT_IS_HIGH_VARIABILITY                                96
#define FEAT_IS_VERY_STILL                                      97
#define FEAT_BREATHING_RATE_VARIABILITY                         98
#define FEAT_BREATHING_STABILITY                                99
#define FEAT_SNORING_VARIABILITY                                100
#define FEAT_SNORING_NORMALIZED                                 101
#define FEAT_SNORING_PERCENTILE                                 102
#define FEAT_ENERGY_PEAK_RATIO                                  103
#define FEAT_TOTAL_TO_RMS_RATIO                                 104
#define FEAT_ENERGY_ROLLING_MEAN                                105
#define FEAT_ENERGY_ROLLING_STD                                 106
#define FEAT_IS_SILENT                                          107
#define FEAT_SPECTRAL_RICHNESS                                  108
#define FEAT_SPECTRAL_STABILITY                                 109
#define FEAT_SPECTRAL_CENTROID_NORMALIZED                       110
#define FEAT_ACTIVITY_VARIABILITY                               111
#define FEAT_CREST_VARIABILITY                                  112
#define FEAT_IMPULSIVENESS_SCORE                                113
#define FEAT_LOW_TO_HIGH_RATIO                                  114
#define FEAT_MID_TO_TOTAL_RATIO                                 115
#define FEAT_FREQUENCY_CENTER_OF_MASS                           116

#define NUM_FEATURES 117

#endif // FEATURES_AUDIO_H
