/*
 * Auto-generated by export_audio_to_c.py — DO NOT EDIT MANUALLY
 * StandardScaler parameters for the 117-feature audio-enhanced model.
 *
 * Call apply_scaling(raw, scaled) before score().
 */

#ifndef SCALER_AUDIO_H
#define SCALER_AUDIO_H

#define NUM_FEATURES 117

static const double SCALER_MEAN[117] = {
    0.6976704315,  // 0: ax_mean
    0.0034746009,  // 1: ax_std
    0.6903752606,  // 2: ax_min
    0.7060810876,  // 3: ax_max
    -0.0573361218,  // 4: ay_mean
    0.0029985378,  // 5: ay_std
    -0.0643320258,  // 6: ay_min
    -0.0505813568,  // 7: ay_max
    0.6509560593,  // 8: az_mean
    0.0038939515,  // 9: az_std
    0.6413685919,  // 10: az_min
    0.6584619511,  // 11: az_max
    0.8543091848,  // 12: gx_mean
    0.2030921029,  // 13: gx_std
    0.2880597479,  // 14: gx_min
    1.4205305726,  // 15: gx_max
    -3.5045299905,  // 16: gy_mean
    0.3031371209,  // 17: gy_std
    -4.3897526093,  // 18: gy_min
    -2.5982993621,  // 19: gy_max
    1.8571210056,  // 20: gz_mean
    0.1970384143,  // 21: gz_std
    1.3411202738,  // 22: gz_min
    2.4056604948,  // 23: gz_max
    23.7545382412,  // 24: tempC_mean
    0.0260826776,  // 25: tempC_std
    23.6990586588,  // 26: tempC_min
    23.8053648670,  // 27: tempC_max
    421.1013748001,  // 28: zcr_mean
    0.0648617799,  // 29: energy_std
    0.3392624065,  // 30: energy_max
    23823.3816181396,  // 31: very_low_power
    0.0939644212,  // 32: very_low_ratio
    128923.2207207452,  // 33: low_power
    0.7193076136,  // 34: low_ratio
    30363.9940532116,  // 35: snoring_power
    29499.3044930553,  // 36: mid_power
    0.0190315688,  // 37: mid_ratio
    16346.8604239544,  // 38: high_power
    0.0064666000,  // 39: high_ratio
    0.9993573573,  // 40: silence_ratio
    7.9782532059,  // 41: crest_factor
    1.0213023057,  // 42: acc_mag
    0.0064109367,  // 43: acc_mag_std
    1.0318871383,  // 44: acc_mag_max
    1.0118496900,  // 45: acc_mag_min
    4.0720426218,  // 46: gyro_mag
    0.4399724726,  // 47: gyro_mag_std
    4.8209446730,  // 48: gyro_mag_max
    5.0084256381,  // 49: gyro_mag_min
    5.0933449276,  // 50: total_movement
    0.4463834093,  // 51: total_movement_std
    0.2514308723,  // 52: movement_ratio
    3.0507403161,  // 53: movement_balance
    1.0212972265,  // 54: patient_acc_mean
    0.0037092530,  // 55: patient_acc_std
    1.0217737432,  // 56: patient_acc_median
    4.0717403332,  // 57: patient_gyro_mean
    0.1654114265,  // 58: patient_gyro_std
    0.3370872977,  // 59: patient_wake_ratio
    0.0014132175,  // 60: acc_mag_normalized
    0.0039007204,  // 61: gyro_mag_normalized
    0.9995357203,  // 62: acc_vs_patient_median
    0.5049808394,  // 63: acc_percentile
    0.5030317910,  // 64: gyro_percentile
    0.0053139378,  // 65: relative_activity
    1.0144953520,  // 66: acc_mag_prev
    4.0443451531,  // 67: gyro_mag_prev
    5.0588405051,  // 68: total_movement_prev
    0.0068069537,  // 69: acc_mag_diff
    0.0276974688,  // 70: gyro_mag_diff
    0.0076111804,  // 71: acc_mag_diff_abs
    0.0893772462,  // 72: gyro_mag_diff_abs
    1.0212735029,  // 73: acc_mag_rolling_mean_3
    1.0212379697,  // 74: acc_mag_rolling_mean_5
    0.0007066560,  // 75: acc_mag_rolling_std_3
    0.0008763612,  // 76: acc_mag_rolling_std_5
    0.2486385561,  // 77: is_movement_bout
    2.4039209585,  // 78: movement_bout_count
    0.2358798817,  // 79: is_stillness
    2.2744670920,  // 80: stillness_duration
    0.4462065005,  // 81: ax_dominance
    0.1414847345,  // 82: ay_dominance
    0.4123081331,  // 83: az_dominance
    -0.6775215794,  // 84: tilt_estimate
    6.6064128137,  // 85: ax_ay_ratio
    0.2936079843,  // 86: position_change_indicator
    0.0007779679,  // 87: num_position_changes
    40.1173020072,  // 88: time_since_start_min
    2.8007160282,  // 89: sleep_cycle_phase
    0.0917020650,  // 90: sleep_cycle_sin
    -0.0491963424,  // 91: sleep_cycle_cos
    0.0063551777,  // 92: acc_coefficient_of_variation
    0.1051014452,  // 93: gyro_coefficient_of_variation
    0.0200374482,  // 94: acc_range
    -0.1874809651,  // 95: gyro_range
    0.0003111872,  // 96: is_high_variability
    0.0000000000,  // 97: is_very_still
    93.2118494354,  // 98: breathing_rate_variability
    6690.7654689604,  // 99: breathing_stability
    19294.4644521210,  // 100: snoring_variability
    0.0021846408,  // 101: snoring_normalized
    0.5061702088,  // 102: snoring_percentile
    104.8893813591,  // 103: energy_peak_ratio
    545.2356259376,  // 104: total_to_rms_ratio
    0.0011355596,  // 105: energy_rolling_mean
    0.0002351588,  // 106: energy_rolling_std
    1.0000000000,  // 107: is_silent
    0.8845174552,  // 108: spectral_richness
    25.2479528239,  // 109: spectral_stability
    -0.0014690373,  // 110: spectral_centroid_normalized
    0.0010265644,  // 111: activity_variability
    4.5076446470,  // 112: crest_variability
    0.7816341928,  // 113: impulsiveness_score
    157.4857518428,  // 114: low_to_high_ratio
    4568.4423713464,  // 115: mid_to_total_ratio
    96.4937617941  // 116: frequency_center_of_mass
};

static const double SCALER_SCALE[117] = {
    0.1265256728,  // 0: ax_mean
    0.0113539265,  // 1: ax_std
    0.1292778881,  // 2: ax_min
    0.1305293131,  // 3: ax_max
    0.2673622614,  // 4: ay_mean
    0.0103247620,  // 5: ay_std
    0.2680109463,  // 6: ay_min
    0.2689484248,  // 7: ay_max
    0.2047859696,  // 8: az_mean
    0.0150556090,  // 9: az_std
    0.2112773014,  // 10: az_min
    0.2055776609,  // 11: az_max
    0.2243081470,  // 12: gx_mean
    0.8859308408,  // 13: gx_std
    3.8372011339,  // 14: gx_min
    3.8085117904,  // 15: gx_max
    0.3028884649,  // 16: gy_mean
    1.5146234535,  // 17: gy_std
    6.5200886740,  // 18: gy_min
    6.4287252764,  // 19: gy_max
    0.2084652401,  // 20: gz_mean
    0.9890068850,  // 21: gz_std
    2.9302500021,  // 22: gz_min
    4.2535378564,  // 23: gz_max
    0.6930784317,  // 24: tempC_mean
    0.0240902596,  // 25: tempC_std
    0.7155239658,  // 26: tempC_min
    0.6787885193,  // 27: tempC_max
    72.4422178045,  // 28: zcr_mean
    1.1279234478,  // 29: energy_std
    5.2302740352,  // 30: energy_max
    303281.5170319234,  // 31: very_low_power
    0.0394500619,  // 32: very_low_ratio
    662027.7453414693,  // 33: low_power
    0.0718309983,  // 34: low_ratio
    197653.8857669567,  // 35: snoring_power
    817731.4905576126,  // 36: mid_power
    0.0394368574,  // 37: mid_ratio
    521684.7506424974,  // 38: high_power
    0.0154056511,  // 39: high_ratio
    0.0021403800,  // 40: silence_ratio
    9.6346991616,  // 41: crest_factor
    0.0120611531,  // 42: acc_mag
    0.0213848205,  // 43: acc_mag_std
    0.0390305309,  // 44: acc_mag_max
    0.0380949241,  // 45: acc_mag_min
    0.2538804371,  // 46: gyro_mag
    2.0088502073,  // 47: gyro_mag_std
    8.0771663715,  // 48: gyro_mag_max
    7.8669699720,  // 49: gyro_mag_min
    0.2522218170,  // 50: total_movement
    2.0271428837,  // 51: total_movement_std
    0.0126904765,  // 52: movement_ratio
    0.2560969553,  // 53: movement_balance
    0.0101102762,  // 54: patient_acc_mean
    0.0054359909,  // 55: patient_acc_std
    0.0094618028,  // 56: patient_acc_median
    0.0565273553,  // 57: patient_gyro_mean
    0.1834770559,  // 58: patient_gyro_std
    0.2264111065,  // 59: patient_wake_ratio
    1.0053175165,  // 60: acc_mag_normalized
    1.0038990995,  // 61: gyro_mag_normalized
    0.0070565217,  // 62: acc_vs_patient_median
    0.2880343251,  // 63: acc_percentile
    0.2883929240,  // 64: gyro_percentile
    1.3542862734,  // 65: relative_activity
    0.0841125852,  // 66: acc_mag_prev
    0.4174705031,  // 67: gyro_mag_prev
    0.4854691910,  // 68: total_movement_prev
    0.0828291022,  // 69: acc_mag_diff
    0.4825501260,  // 70: gyro_mag_diff
    0.0827590763,  // 71: acc_mag_diff_abs
    0.4750089281,  // 72: gyro_mag_diff_abs
    0.0115734449,  // 73: acc_mag_rolling_mean_3
    0.0114905325,  // 74: acc_mag_rolling_mean_5
    0.0039393029,  // 75: acc_mag_rolling_std_3
    0.0041981821,  // 76: acc_mag_rolling_std_5
    0.4322238130,  // 77: is_movement_bout
    4.0409723043,  // 78: movement_bout_count
    0.4245474804,  // 79: is_stillness
    3.8442899780,  // 80: stillness_duration
    0.1242267656,  // 81: ax_dominance
    0.0799810588,  // 82: ay_dominance
    0.0919629566,  // 83: az_dominance
    36.6383129410,  // 84: tilt_estimate
    9.9163304604,  // 85: ax_ay_ratio
    3.7157323653,  // 86: position_change_indicator
    0.0278812251,  // 87: num_position_changes
    24.7080389727,  // 88: time_since_start_min
    1.7249465271,  // 89: sleep_cycle_phase
    0.7064895044,  // 90: sleep_cycle_sin
    0.7000307360,  // 91: sleep_cycle_cos
    0.0229844117,  // 92: acc_coefficient_of_variation
    0.4671928910,  // 93: gyro_coefficient_of_variation
    0.0660772647,  // 94: acc_range
    6.1370615690,  // 95: gyro_range
    0.0176377533,  // 96: is_high_variability
    1.0000000000,  // 97: is_very_still
    1893.7027651454,  // 98: breathing_rate_variability
    81521.5190541826,  // 99: breathing_stability
    177309.1832032375,  // 100: snoring_variability
    0.9928202358,  // 101: snoring_normalized
    0.2882441969,  // 102: snoring_percentile
    290.1605152428,  // 103: energy_peak_ratio
    399.7689517336,  // 104: total_to_rms_ratio
    0.0004853772,  // 105: energy_rolling_mean
    0.0006449560,  // 106: energy_rolling_std
    1.0000000000,  // 107: is_silent
    0.2210254449,  // 108: spectral_richness
    76.2415419548,  // 109: spectral_stability
    0.9889255488,  // 110: spectral_centroid_normalized
    0.0016875182,  // 111: activity_variability
    8.0927823799,  // 112: crest_variability
    10.6456694919,  // 113: impulsiveness_score
    59.6171320872,  // 114: low_to_high_ratio
    9465.2314267697,  // 115: mid_to_total_ratio
    117.5722387981  // 116: frequency_center_of_mass
};

/* Scale raw feature vector in-place equivalent. */
static inline void apply_scaling(const double raw[117],
                                  double       out[117]) {
    for (int i = 0; i < 117; i++)
        out[i] = (raw[i] - SCALER_MEAN[i]) / SCALER_SCALE[i];
}

#endif // SCALER_AUDIO_H
