/*
 * Feature Indices
 * Auto-generated - DO NOT EDIT
 */

#ifndef FEATURES_H
#define FEATURES_H

// Feature indices for input array
#define FEAT_AX_MEAN                                            0
#define FEAT_AX_STD                                             1
#define FEAT_AX_MIN                                             2
#define FEAT_AX_MAX                                             3
#define FEAT_AY_MEAN                                            4
#define FEAT_AY_STD                                             5
#define FEAT_AY_MIN                                             6
#define FEAT_AY_MAX                                             7
#define FEAT_AZ_MEAN                                            8
#define FEAT_AZ_STD                                             9
#define FEAT_AZ_MIN                                             10
#define FEAT_AZ_MAX                                             11
#define FEAT_GX_MEAN                                            12
#define FEAT_GX_STD                                             13
#define FEAT_GX_MIN                                             14
#define FEAT_GX_MAX                                             15
#define FEAT_GY_MEAN                                            16
#define FEAT_GY_STD                                             17
#define FEAT_GY_MIN                                             18
#define FEAT_GY_MAX                                             19
#define FEAT_GZ_MEAN                                            20
#define FEAT_GZ_STD                                             21
#define FEAT_GZ_MIN                                             22
#define FEAT_GZ_MAX                                             23
#define FEAT_TEMPC_MEAN                                         24
#define FEAT_TEMPC_STD                                          25
#define FEAT_TEMPC_MIN                                          26
#define FEAT_TEMPC_MAX                                          27
#define FEAT_ENERGY_STD                                         28
#define FEAT_ENERGY_MAX                                         29
#define FEAT_MIC_RMS_MEAN                                       30
#define FEAT_MIC_RMS_STD                                        31
#define FEAT_MIC_RMS_MIN                                        32
#define FEAT_MIC_RMS_MAX                                        33
#define FEAT_ZCR_MEAN                                           34
#define FEAT_ZCR_STD                                            35
#define FEAT_ZCR_MIN                                            36
#define FEAT_ZCR_MAX                                            37
#define FEAT_RMS_ENERGY                                         38
#define FEAT_TOTAL_ENERGY                                       39
#define FEAT_ENERGY_STD                                         40
#define FEAT_ENERGY_MAX                                         41
#define FEAT_ZCR                                                42
#define FEAT_SILENCE_RATIO                                      43
#define FEAT_ACTIVITY_RATIO                                     44
#define FEAT_PEAK_TO_PEAK                                       45
#define FEAT_CREST_FACTOR                                       46
#define FEAT_BREATHING_POWER                                    47
#define FEAT_BREATHING_RATIO                                    48
#define FEAT_VERY_LOW_POWER                                     49
#define FEAT_VERY_LOW_RATIO                                     50
#define FEAT_LOW_POWER                                          51
#define FEAT_LOW_RATIO                                          52
#define FEAT_MID_POWER                                          53
#define FEAT_MID_RATIO                                          54
#define FEAT_HIGH_POWER                                         55
#define FEAT_HIGH_RATIO                                         56
#define FEAT_ACC_MAG                                            57
#define FEAT_ACC_MAG_STD                                        58
#define FEAT_ACC_MAG_MAX                                        59
#define FEAT_ACC_MAG_MIN                                        60
#define FEAT_ACC_MAG_RANGE                                      61
#define FEAT_GYRO_MAG                                           62
#define FEAT_GYRO_MAG_STD                                       63
#define FEAT_GYRO_MAG_MAX                                       64
#define FEAT_GYRO_MAG_MIN                                       65
#define FEAT_GYRO_MAG_RANGE                                     66
#define FEAT_TOTAL_MOVEMENT                                     67
#define FEAT_TOTAL_MOVEMENT_STD                                 68
#define FEAT_AX_DOMINANCE                                       69
#define FEAT_AY_DOMINANCE                                       70
#define FEAT_AZ_DOMINANCE                                       71
#define FEAT_GRAVITY_X                                          72
#define FEAT_GRAVITY_Y                                          73
#define FEAT_GRAVITY_Z                                          74
#define FEAT_TILT_ESTIMATE                                      75
#define FEAT_PATIENT_ACC_MAG_MEAN                               76
#define FEAT_PATIENT_ACC_MAG_STD                                77
#define FEAT_PATIENT_GYRO_MAG_MEAN                              78
#define FEAT_PATIENT_GYRO_MAG_STD                               79
#define FEAT_PATIENT_TOTAL_MOVEMENT_MEAN                        80
#define FEAT_PATIENT_TOTAL_MOVEMENT_STD                         81
#define FEAT_PATIENT_WAKE_RATIO                                 82
#define FEAT_PATIENT_SLEEP_RATIO                                83
#define FEAT_ACC_MAG_NORMALIZED                                 84
#define FEAT_GYRO_MAG_NORMALIZED                                85
#define FEAT_TOTAL_MOVEMENT_NORMALIZED                          86
#define FEAT_ACC_MAG_ZSCORE                                     87
#define FEAT_GYRO_MAG_ZSCORE                                    88
#define FEAT_ACC_MAG_PREV                                       89
#define FEAT_ACC_MAG_DIFF                                       90
#define FEAT_ACC_MAG_ABS_DIFF                                   91
#define FEAT_GYRO_MAG_PREV                                      92
#define FEAT_GYRO_MAG_DIFF                                      93
#define FEAT_GYRO_MAG_ABS_DIFF                                  94
#define FEAT_TOTAL_MOVEMENT_PREV                                95
#define FEAT_TOTAL_MOVEMENT_DIFF                                96
#define FEAT_TOTAL_MOVEMENT_ABS_DIFF                            97
#define FEAT_ACC_MAG_NORMALIZED_PREV                            98
#define FEAT_ACC_MAG_NORMALIZED_DIFF                            99
#define FEAT_ACC_MAG_NORMALIZED_ABS_DIFF                        100
#define FEAT_GYRO_MAG_NORMALIZED_PREV                           101
#define FEAT_GYRO_MAG_NORMALIZED_DIFF                           102
#define FEAT_GYRO_MAG_NORMALIZED_ABS_DIFF                       103
#define FEAT_TIME_SINCE_START_MIN                               104
#define FEAT_TIME_SINCE_START_HOURS                             105
#define FEAT_TIME_BIN                                           106
#define FEAT_ACC_CV                                             107
#define FEAT_GYRO_CV                                            108
#define FEAT_MOVEMENT_CONSISTENCY                               109
#define FEAT_HIGH_ACC_FLAG                                      110
#define FEAT_HIGH_GYRO_FLAG                                     111
#define FEAT_HIGH_MOVEMENT_FLAG                                 112
#define FEAT_BREATH_PROXY                                       113
#define FEAT_BREATH_AMPLITUDE                                   114
#define FEAT_BREATH_DEPTH_SCORE                                 115
#define FEAT_BREATHING_RATE_VARIABILITY                         116
#define FEAT_BREATHING_ROLLING_STD_5                            117
#define FEAT_BREATHING_DIFF_PREV                                118
#define FEAT_BREATHING_ABS_DIFF                                 119
#define FEAT_BREATHING_STABILITY                                120
#define FEAT_MOVEMENT_BOUT_COUNT                                121
#define FEAT_MOVEMENT_BOUT_DURATION                             122
#define FEAT_STILLNESS_DURATION                                 123
#define FEAT_MOVEMENT_FRAGMENTATION_INDEX                       124
#define FEAT_TILT_DIFF                                          125
#define FEAT_POSITION_CHANGE_INDICATOR                          126
#define FEAT_NUM_POSITION_CHANGES                               127
#define FEAT_ACC_MAG_ROLLING_MEAN_3                             128
#define FEAT_ACC_MAG_ROLLING_STD_3                              129
#define FEAT_ACC_MAG_ROLLING_MEAN_5                             130
#define FEAT_ACC_MAG_ROLLING_STD_5                              131
#define FEAT_SLEEP_CYCLE_SIN                                    132
#define FEAT_SLEEP_CYCLE_COS                                    133

#define NUM_FEATURES 134

#endif // FEATURES_H
